version: '3.1'
services:
  robosaur:
    build:
      context: .
      dockerfile: robosaur.Dockerfile
    environment:
      - MONGODB_CONNSTRING=mongodb://vulcan:vulcan@mongodb:27017/
    ports:
      - 6969:6969
    volumes:
      - ./docker-config:/home/robosaur/config
      - ./docker-state:/home/robosaur/state
      - ./docker-logs:/home/robosaur/logs
    extra_hosts:
      - 'host.docker.internal:172.17.0.1'
  mongodb:
    image: mongo:4.2
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=vulcan
      - MONGO_INITDB_ROOT_PASSWORD=vulcan
      - MONGO_INITDB_DATABASE=vulcan
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: vulcan
      ME_CONFIG_MONGODB_ADMINPASSWORD: vulcan
      ME_CONFIG_MONGODB_URL: mongodb://vulcan:vulcan@mongo:27017/
