version: '3.1'
services:
  robosaur:
    build:
      context: .
      dockerfile: robosaur.Dockerfile
    ports:
      - 6969
    volumes:
      - ./sample/rex/config_rex.json:/home/robosaur/config/config.json
      - ./sample/rex/logs/producer:/home/robosaur/logs
    extra_hosts:
      - 'host.docker.internal:172.17.0.1'
    environment:
      - COMMAND_NAME=start-producer
    healthcheck:
      test: ["CMD", "wget", "http://localhost:3000/health", "-O", "-"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: always
  consumer:
    build:
      context: .
      dockerfile: robosaur.Dockerfile
    deploy:
      mode: replicated
      replicas: 2
    volumes:
      - ./sample/rex/config_rex.json:/home/robosaur/config/config.json
      - ./sample/rex/logs/consumers:/home/robosaur/logs
    extra_hosts:
      - 'host.docker.internal:172.17.0.1'
    environment:
      - COMMAND_NAME=start-consumer
    healthcheck:
      test: ["CMD", "wget", "http://localhost:3000/health", "-O", "-"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: always
  rabbitmq:
    image: rabbitmq:3.11-management
    volumes:
      - ./rabbitmqdata:/var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: vulcan
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: vulcan
  #     ME_CONFIG_MONGODB_URL: mongodb://vulcan:vulcan@mongodb:27017/
  # mongodb:
  #   image: mongo:4.2
  #   restart: always
  #   ports:
  #     - 27017:27017
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=vulcan
  #     - MONGO_INITDB_ROOT_PASSWORD=vulcan
  #     - MONGO_INITDB_DATABASE=vulcan