version: '3.1'
services:
  robosaur:
    build:
      context: .
      dockerfile: robosaur.Dockerfile
    ports:
      - 6969:6969
    volumes:
      - ./sample/rex/config_rex.json:/home/robosaur/config/config.json
      - ./sample/rex/state:/home/robosaur/state
      - ./sample/rex/logs:/home/robosaur/logs
    extra_hosts:
      - 'host.docker.internal:172.17.0.1'
    healthcheck:
      test: ['CMD', 'npm', 'start', 'health-check']
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s
    restart: always
  mongodb:
    image: mongo:4.2
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=vulcan
      - MONGO_INITDB_ROOT_PASSWORD=vulcan
      - MONGO_INITDB_DATABASE=vulcan
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: vulcan
      ME_CONFIG_MONGODB_ADMINPASSWORD: vulcan
      ME_CONFIG_MONGODB_URL: mongodb://vulcan:vulcan@mongodb:27017/
