version: '3.1'

services:
  mongo:
    image: mongo:4.2
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: vulcan
      MONGO_INITDB_ROOT_PASSWORD: vulcan
      MONGO_INITDB_DATABASE: vulcan

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: vulcan
      ME_CONFIG_MONGODB_ADMINPASSWORD: vulcan
      ME_CONFIG_MONGODB_URL: mongodb://vulcan:vulcan@mongo:27017/
