version: '3.1'
services:
  robosaur:
    image: datasaur/robosaur:${DOCKER_TAG}
    build:
      context: ./../
      args:
        uid: ${USER_ID}
        gid: ${GROUP_ID}
      dockerfile: robosaur.Dockerfile
