version: '3.1'
networks:
  default:
    external:
      name: ${DOCKER_NETWORK_NAME}
volumes:
  rabbitmq_data:
    name: datasaur_rabbitmq_data
services:
  rabbitmq:
    image: rabbitmq:3.11-management
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
  loki:
    image: grafana/loki:2.6.1
    ports:
      - '3100'
    volumes:
      - ./volumes/loki:/loki
  promtail:
    image: grafana/promtail:2.6.1
    volumes:
      - ./loki/promtail-config.yaml:/etc/promtail/config.yml
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers
  grafana:
    image: grafana/grafana:9.2.2
    ports:
      - '3002:3000'
    environment:
      - GF_SERVER_DOMAIN=${DOMAIN}
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s:%(http_port)s/grafana
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    volumes:
      - ./volumes/grafana:/var/lib/grafana
      - ./loki/grafana/provisioning/:/etc/grafana/provisioning/
