version: '3.1'
networks:
  default:
    external:
      name: ${DOCKER_NETWORK_NAME}
services:
  rabbitmq:
    image: rabbitmq:3.11
    volumes:
      - ./rabbitmqdata:/var/lib/rabbitmq
    ports:
      - 5672:5672
