version: '3.1'
services:
  robosaur:
    image: datasaur/robosaur:${DOCKER_TAG}
    container_name: datasaur-robosaur
    env_file:
      - ./robosaur.env
    ports:
      - 6969:6969
    volumes:
      - ./docker-config:/home/robosaur/config
      - ./docker-state:/home/robosaur/state
      - ./docker-logs:/home/robosaur/logs
    